// Generated by CoffeeScript 2.2.4
var cdn, plug, wch;

cdn = require('cara-cdn');

wch = require('wch');

plug = wch.plugin('cara');

plug.on('run', function() {
  return cdn.run({
    log: plug.log
  });
});

plug.on('stop', cdn.stop);

plug.on('add', function(root) {
  return cdn.add(root.path);
});

plug.on('remove', function(root) {
  return cdn.remove(root.path);
});

module.exports = plug;
